"$schema": "http://json-schema.org/draft-04/schema#"
type: "object"
properties:
  homeserver:
    type: "object"
    properties:
      domain:
        type: "string"
      url:
        type: "string"
      mediaUrl:
        type: "string"
  instagram:
    type: "object"
    properties:
      clientId:
        type: "string"
      clientSecret:
        type: "string"
      publicUrlBase:
        type: "string"
      botAppearance:
        type: "object"
        properties:
          displayName:
            type: "string"
          avatarUrl:
            type: "string"